# For more information: https://laravel.com/docs/sail
version: "3"
services:

  app:
    image: mtbossa/raspberry-prod:latest
    restart: always
    ports:
      - "45691:45691"
    env_file:
      - .env
    volumes:
      - ${MEDIAS_FOLDER_PATH}:/intus/public/medias
      - ${DB_FOLDER_PATH}:/intus/data
      - ${LOGS_FOLDER_PATH}:/intus/logs
