# For more information: https://laravel.com/docs/sail
version: "3"
services:

  app:
    image: mtbossa/raspberry-prod:staging
    restart: always
    ports:
      - "45691:45691"
    env_file:
      - .env
    volumes:
      - ${MEDIAS_FOLDER_PATH}:/intus/public/medias
      - ${DB_FOLDER_PATH}:/intus/data
      - ${LOGS_FOLDER_PATH}:/intus/logs

  watchtower:
    image: containrrr/watchtower
    environment:
      REPO_USER: ${REPO_USER}
      REPO_PASS: ${REPO_PASS}
      WATCHTOWER_DEBUG: ${WATCHTOWER_DEBUG}
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_SCHEDULE: "0 0 * * *"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
